services:
  front:
    build:
      context: ./front
    working_dir: /app
    ports:
      - "${PORT_FRONT}:${PORT_FRONT}"
    volumes:
      - ./front:/app
    environment:
      - NODE_ENV=${ENVIRONMENT}

  api:
    # Force developer to create a .env file
    env_file: .env
    command: gunicorn -k uvicorn.workers.UvicornWorker template.api.app:factory_app --bind ${HOST_API}:${PORT_API} -w ${WORKERS_API:-1}
    volumes:
      - ./.env:/app/.env
      - ./data:/app/data
    build:
      context: .
    ports:
      - "${PORT_API}:${PORT_API}"
    develop:
      watch:
        - action: sync
          target: /app
          path: .
          ignore:
            - .venv/
            - __pycache__/
            - "*.pyc"
            - "*.pyo"
        - action: rebuild
          path: ./uv.lock
