services:
  front:
    build:
      context: ./front
    working_dir: /app
    volumes:
      - ./front:/app
    environment:
      - NODE_ENV=${ENVIRONMENT}
#     networks:
#       - internal

  api:
    # Force developer to create a .env file
    env_file: .env
    command: gunicorn -k uvicorn.workers.UvicornWorker template.api.app:factory_app -w ${WORKERS_API:-1} -b 0.0.0.0:8001
    ports:
      - "8001:8001"
    volumes:
      - ./data:/app/data
    build:
      context: .
#     networks:
#       - internal

# networks:
#     internal:
#         driver: bridge
