services:
  front:
    build:
      context: ./front
      args:
        PUBLIC_API_URL: ${DOMAIN_API}
    working_dir: /app
    ports:
      - "${PORT_FRONT}:${PORT_FRONT}"
    volumes:
      - ./front:/app
    environment:
      - PUBLIC_API_URL=${DOMAIN_API}
      - NODE_ENV=${ENVIRONMENT}

  api:
    # Force developer to create a .env file
    command: gunicorn -k uvicorn.workers.UvicornWorker rename.api.app:factory_app --bind ${HOST_API}:${PORT_API} -w ${WORKERS_API:-1}
    volumes:
      - ./.env:/app/.env
      - ./data:/app/data
    build:
      context: .
    ports:
      - "${PORT_API}:${PORT_API}"