[project]
name = "template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Athroniaeth", email = "pierre.chaumont@hotmail.fr" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
clean-fastapi-template = "clean_fastapi_template:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
